application: cloudkeys
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin

- url: /js/(.*)
  static_files: templates/js/\1
  upload: templates/js/(.*)

- url: /css/(.*)
  static_files: templates/css/\1
  upload: templates/css/(.*)

- url: /images/(.*)
  static_files: templates/images/\1
  upload: templates/images/(.*)

- url: /favicon.ico
  static_files: templates/images/favicon.ico
  upload: templates/images/favicon.ico

- url: /api/.*
  script: api/api.py

- url: /.*
  script: index.py

- url: /
  static_files: templates/index.html
  upload: templates/index.html
